### ISSUE TITLE
Should we drop the Template page altogether?

### ISSUE THREAD

**Issue by Lawouach** [atomist/end-user-documentation#102]
The page is short and has more content describing how we actually discourage it than how to use them. With the move away from the DSL, there might be no point in even mentioning them any longer?

**Comment by ddgenome** [comment]
We still have the functionality and there probably are cases where it is useful. I'd vote keep it with the note about preferring not to use it.

**Comment by ddgenome** [comment]
I'm going to close this. As long as the feature is available, it should be documented.
