### ISSUE TITLE
Command Handler documentation is incorrect

### ISSUE THREAD

**Issue by kipz** [atomist/end-user-documentation#105]
http://docs.atomist.com/user-guide/rug/commands/

It states:

`the handler calls our editor, but could also make externals calls, and responds with a message.` 

but actually does no such thing.

**Comment by Lawouach** [comment]
I think we haven't had the chance to properly work on that one yet sadly.

**Comment by kipz** [comment]
Understood, but it's better to have less documentation that incorrect/conflicting documentation IMO. There are executors and handlers in there too!

**Comment by Lawouach** [comment]
I guess we're doing what we can ;)

**Comment by kipz** [comment]
My point is, we can do less and it'll be better by not adding that stuff. Should I go ahead and remove it?

**Comment by Lawouach** [comment]
If it's wrong, I'm certainly fine with removing it for sure.

**Comment by ddgenome** [comment]
If you don't want it in there in its present form, comment it out in the mkdocs.yml but leave the file. Be sure to fix any broken links.
