### ISSUE TITLE
Table of Contents on right is weird to me

### ISSUE THREAD

**Issue by jpwarren** [atomist/end-user-documentation#112]
The table of contents at the right is not where I expect it to be.

I expect it to be part of the navigation at the left, with the table of contents items to nest inside the document I'm reading.

**Comment by Lawouach** [comment]
That never really bothered me, the left menu is for site navigation whereas the right is for page navigation. That being said, if it is indeed a real issue, we would need to change the Material theme more extensively than usual.

http://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme

**Comment by jpwarren** [comment]
If it's just me and people generally aren't confused, then it doesn't matter. I'll adapt. :)
