### ISSUE TITLE
Adding CLI to Getting Started prerequisites

### ISSUE THREAD

**Issue by russmiles** [atomist/end-user-documentation#113]
We should reference the Rug CLI in the Getting Started pre-requisites page as this is the main Rug authoring and publishing tool that is used in the Getting Started.

**Comment by ddgenome** [comment]
Do we really want to do that?

**Comment by russmiles** [comment]
It's something I'd like to avoid but since we are encouraging folks to write their own handlers and then moving onto generators and editors fairly rapidly... it feels like a first class citizen. At the moment it's introduced later, and maybe pre requisite is the wrong term. Maybe as part of a Atomist Tools page/list

**Comment by russmiles** [comment]
And it's actually a necessary part of publishing handlers as part of the Getting Started, so feels like a pre-req?

**Comment by ddgenome** [comment]
Yeah, I know. I'm just afraid a giant getting started guide may be off-putting to some. We can discuss later.
