### ISSUE TITLE
commands and editors example nearly the same

### ISSUE THREAD

**Issue by janekdb** [atomist/end-user-documentation#119]
Examples are nearly the same but `commands` seems to have wrong description.

https://docs.atomist.com/user-guide/rug/commands/
`@CommandHandler("AddMarkdownDocument","Runs the SetLicense editor on a bunch of my repos")`

https://docs.atomist.com/user-guide/rug/editors/ - AddMarkdownDocument

Second example should be different?

**Comment by Lawouach** [comment]
Indeed. The changes have been merged in but not yet published so they are not visible. We should cut a new docs release.
