### ISSUE TITLE
Make introduction-overview more 'active'

### ISSUE THREAD

**Issue by russmiles** [atomist/end-user-documentation#120]
At the moment the Overview on concepts, and in possibly other areas of our documentation, I think we tend to be a little passive rather than active. I'll add a comment here to illustrate what I mean.

**Comment by russmiles** [comment]
Emphasis on "you" and "your". This is a sample of what I have in mind:

--- Current ---

Rug is a programming model and runtime.

The Rug programming model defines the interface, which is "What events
does this program respond to?" and "How does it respond?".  Programs
that implement this model are called Rugs, and they execute inside a
Rug runtime.

...

--- Proposed ---

Rug is the programming model and runtime that you use to define, "What events
do I want Atomist to respond to?" and, "How does Atomist then respond?".  Your programs
that implement this model are called Rugs, are packaged and distributed in Rug archives, and are eventually executed inside a Rug runtime.

...

**Comment by ddgenome** [comment]
Personally, I'd vote no, but am happy to cede to the majority.

**Comment by ddgenome** [comment]
As we discussed yesterday, please give this a go and then submit a PR.
