### ISSUE TITLE
Reorganize Getting Started

### ISSUE THREAD

**Issue by ddgenome** [atomist/end-user-documentation#125]
The Getting Started guide is getting long and, possibly, intimidating. Reorganize into two subsections: set up and using Atomist. The first subsection will cover the prerequisites, Slack, GitHub, and CI. The latter section will cover interacting with Atomist in Slack and writing your own Rugs.

**Comment by Lawouach** [comment]
I have been thinking about how to best organise the Getting Started and it isn't easy. Do we consider that inviting the bot to your team has gotten you started? Then, everything else is considered "integration". But two questions come to mind: why "Adding the bot to your team" not just integration? Can you do anything remotely useful without actually linking to GH as well? 

The split isn't easy.

**Comment by ddgenome** [comment]
I have created a GitHub org (atomist-docs) and user (adaist) and Slack team (atomist-docs) and user (ada) so we can have unified workflow and screen shots in the end-user documentation.

**Comment by ddgenome** [comment]
The reorg is done. We still need updated imagery and moving code into this repo.
