### ISSUE TITLE
Move code used in end-user-docs to separate repo

### ISSUE THREAD

**Issue by jrday** [atomist/end-user-documentation#158]
After talking with @ddgenome, it seems time to separate out the code from the prose in this repo. @ddgenome will update the doc build process to bring in code from a separate repo.

One goal of moving out the code is to make sure it is kept current with versions as they get updated (rug, @atomist/rugs, etc.)

What's to do?

- [ ] Create the repo from a generator
- [ ] Move any code that is currently under `end-user-documentation/.atomist` to a new repo
- [ ] README in the new repo explaining what it and how it's used

**Comment by ddgenome** [comment]
The cleanest way to create a proper Rug project is to use the minimal generator, NewRugProject, and then run the AddTypeScript editor on the project.

**Comment by ddgenome** [comment]
doc-rugs repo created
