### ISSUE TITLE
inconsitent use of Jenkins urls at http://docs.atomist.com/getting-started/jenkins/

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist/end-user-documentation#160]
The text at ```On the "Job Notifications" configuration tab, set the "Notifications Endpoints" URL to https://webhook.atomist.com/jenkins and check that the other parameters match the information shown below.```
should switch the url to webhook.atomist.com/atomist/jenkins

The code snippet in groovy is correct.

The image below the above text is also incorrect

**Comment by ddgenome** [comment]
Fixed in 74c2cb1a3ddeff9cca5f84b0bfbef23dad456352
