### ISSUE TITLE
Clarify cli login is real password, not an access token, in CLI setup tutorial

### ISSUE THREAD

**Issue by jpwarren** [atomist/end-user-documentation#161]
I have an access token set up for providing access to my GitHub to external apps and for code push.

When doing `rug login` in the Tutorial, I attempted to use my GitHub access token instead of the actual password. The command silently fails, and the exit code is 0, so it looks like it succeeded, but it hasn't.

Need to clarify in the documentation to use your actual password for GitHub, not any configured access tokens.

**Comment by russmiles** [comment]
Possibly this might be a refinement/enhancement issue for the CLI as well to perhaps do some sort of test execution when the credentials have been provided so some feedback can be given in the tool as well @cdupuis ?

**Comment by cdupuis** [comment]
@jpwarren how does the cli `silently fail`? I agree with @russmiles this being a bug in the CLI.

**Comment by jpwarren** [comment]
The command simply exits, with error code `0`.

If you get your credential wrong, you get an error: `Provided credentials are invalid. Please try again with correct credentials.` but if you use a correct auth token, you don't get this error.

It doesn't prompt for multi-factor auth (which was a clue for me, because I have MFA turned on), it just exits.

**Comment by cdupuis** [comment]
What it returns, did it write a github token into your ~/.atomist/cli.yml?

**Comment by jpwarren** [comment]
I don't think so.

I successfully authenticated using my actual password, so I don't have the same initial conditions any more, but if I re-run the login command to test now, I get the same behaviour, and I don't see any updates to `~/.atomist/cli.yml` and the file modify timestamp is the same.

**Comment by ddgenome** [comment]
I've added text in the docs that make this more clear. I'll open an issue in rug-cli about the erroneous successful exit status and then close this.
