### ISSUE TITLE
"Reference Documentation -> Rug -> Overview - Rug API documentation" link not working

### ISSUE THREAD

**Issue by tanya-coding** [atomist/end-user-documentation#167]
![image](https://cloud.githubusercontent.com/assets/19268924/25964328/0f0d9df0-364a-11e7-9cc8-774437a81ce0.png)

**Comment by ddgenome** [comment]
This is fixed in a recent master commit, just not published yet a50c8d5495fb7672a5c3510fd2e5e7d5541f5a52

It was working until we fixed the scaladoc-no-longer-getting-published bug in Rug. Now that they are, it broke and we needed to revert.
