### ISSUE TITLE
Clean up project creation page

### ISSUE THREAD

**Issue by WillGardella** [atomist/end-user-documentation#207]
I did one pass of copy editing on the generator example, but it needs 

1. a better introduction into the generator samples - it doesn't explain what they do, it should
2. someone should check my copy edits, I added information that might be wrong or poorly written
3. the wording in the example column of the table is strange and could use some clean up
4. I think the doc would be a lot better if it gave a simple step by step guide how to clone, configure and run the "new automation generator".
5. I would prefer if the table could find all its examples in the same generator - is that possible?

**Comment by jessitron** [comment]
It's all possible. By writing a generator whose purpose is to be a clear sample.
Not today.

I would like the new automation generator to be a default one that is available to all teams. but we'd also like it to be better; it's minimal now and copies the samples. So it's too simple, while the initializr example is more robust, but too abstract to be a good sample.

When we are running a version of initializr, that changes our messaging here too.

There's really a LOT needed here. What do we want for _today_ ?

**Comment by WillGardella** [comment]
Not a priority right now.
