### ISSUE TITLE
Review stripped down quick start

### ISSUE THREAD

**Issue by WillGardella** [atomist/end-user-documentation#208]
@claymccoy @ddgenome I tried to strip down the quick start to a more "run and gun" style - users should be able to run commands and "do stuff" with little explanation or reading required. My edits aren't perfect, but I wanted to run it by you two. I would like to refer people to the quick start and rely on that quite a bit, and point people to the commands and events and other sections as needed.

**Comment by claymccoy** [comment]
It seems weird that we show them code before they clone the project. Why show code at all here, we can link to the file in the GitHub project and they can take a look if they are curious. Still a lot of redundancy with the GraphQL and Events docs. Dive is just another listing of a lot of the stuff in the outline to the left. 
I still think this should be cut down further and combined with "Using Atomist".

**Comment by claymccoy** [comment]
The event handler example is overly complicated. Much more complicated than the one used in the dedicated events section. That likely gives the perception that it is harder than it actually is to create an event handler.

**Comment by ddgenome** [comment]
I don't think this should go under "Using Atomist", since it is specifically focused on getting people started with developing automations.

I've cut down the even example a bit more. I'll push soon.

**Comment by ddgenome** [comment]
Stripped down and moved out of developer guide. #214 

Closing.
