### ISSUE TITLE
Split conventions into General, Rug DSL and Rug TypeScript

### ISSUE THREAD

**Issue by russmiles** [atomist/end-user-documentation#24]
The current Rug Conventions document has grown considerably and is beginning to break the navigation rendering. One option here is to attempt to break things out based on general purpose, Rug DSL and Rug TypeScript specific conventions. This might also prove more scalable generally as other JavaScript-transpiled options become available for Rug.

**Comment by ddgenome** [comment]
No longer relevant. See #103
