### ISSUE TITLE
Remove Rug DSL embeddable Clojure documentation

### ISSUE THREAD

**Issue by kipz** [atomist/end-user-documentation#41]
This has not been supported for some time:

http://docs.atomist.com/reference-docs/rug/escape/rug-clojure/#escaping-into-clojure-through-clojure-blocks

http://docs.atomist.com/reference-docs/rug/escape/rug-clojure/

http://docs.atomist.com/reference-docs/rug/types/rug-core-types-java-class/#operation-eval

**Comment by ddgenome** [comment]
Mentions are removed. The operation-eval is tied to the automated doc generation.

**Comment by ddgenome** [comment]
Rolled out
