### ISSUE TITLE
Extension type names are in old dotted format

### ISSUE THREAD

**Issue by kipz** [atomist/end-user-documentation#42]
http://docs.atomist.com/reference-docs/rug/types/rug-core-types-elm-module/

As far as I know, this is all UpperCamlCase now:

elm.module -> ElmModule

**Comment by ddgenome** [comment]
@russmiles can you run the doc generators to clean up all the types in the generated docs? I'm going through the rest of the docs.

**Comment by ddgenome** [comment]
The automatic doc generation is completely broken. So I'm trying to fix that now.

**Comment by ddgenome** [comment]
Fix, generated, updated, and rolled out.
