### ISSUE TITLE
Parameter newVersion is wrong for operation addOrReplaceDependencyScope

### ISSUE THREAD

**Issue by eddumelendez** [atomist/end-user-documentation#43]
https://github.com/atomist/end-user-documentation/blame/8b360c6be32cbec03ac93a5520aac0958300a49a/docs/reference-docs/rug/types/rug-core-types-pom.md#L76

**Comment by ddgenome** [comment]
Fixed: http://docs.atomist.com/reference-docs/rug/types/rug-core-types-pom/#operation-addorreplacedependencyscope
