### ISSUE TITLE
Warn debian/Ubuntu users about old distributions not supported

### ISSUE THREAD

**Issue by Lawouach** [atomist/end-user-documentation#49]
Our documentation doesn't warn that we can't install the CLI on old Debian/Ubuntu versions. This should be noted clearly to avoid misunderstandings.

**Comment by Lawouach** [comment]
We don't prevent installing on older distributions any longer. See atomist/rug-cli#70

**Comment by ddgenome** [comment]
Can this be closed @Lawouach ?

**Comment by Lawouach** [comment]
I'd say so yes.

We are now supporting trusty all the way to the latest ubuntu. We'll need to update the Debian repository as new version show up but the package won't complain any longer.
