### ISSUE TITLE
Rename Types to Language Extensions and be more DRY

### ISSUE THREAD

**Issue by kipz** [atomist/end-user-documentation#64]
Each Type currently has Core Rug Type in front of it. Making it super tough to find stuff. This should be removed.

![screen shot 2017-02-08 at 09 59 21](https://cloud.githubusercontent.com/assets/1865026/22732331/ade3a71a-ede5-11e6-9266-c46eb61160e0.png)

**Comment by ddgenome** [comment]
This is resolved no?
