### ISSUE TITLE
Revamp front matter to be more inviting and informative

### ISSUE THREAD

**Issue by ddgenome** [atomist/end-user-documentation#86]
Per discussions with @jrday, rework front matter to better motivate understanding, intent, and adoption.

**Comment by ddgenome** [comment]
Reorganize into three main areas:

1.  Atomist overview: motivation, problems solved, how it makes things better
2.  What you can do with Atomist: examples, getting started docs
3.  Reference material

**Comment by russmiles** [comment]
I have some work I wrote up around the motivation that might prove useful to section 1. @ddgenome  ?

**Comment by ddgenome** [comment]
@jrday shared it already, thanks.

**Comment by ddgenome** [comment]
New docs landing page has been pushed out.

**Comment by ddgenome** [comment]
Now thinking of merging "Getting Started", "Guides", and "Atomist in Depth" into just "Getting Started" and "User Guide".

**Comment by ddgenome** [comment]
This is out with 5.2.0
